import logging
from datetime import datetime, timedelta
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from aggregator.search import healthcheck as meili_healthcheck
from aggregator.models import Article, Story, Topic, RawArticlePayload, Edition, EditionStory
from aggregator.story_view import apply_aggregator_filter, annotate_edition_story_flags
from news_fetcher.llm_client import check_llm_status as check_ollama_status

logger = logging.getLogger(__name__)

public = Blueprint("public", __name__)


@public.route("/")
def index():
    return redirect(url_for("admin.list_articles"))


@public.route("/headlines")
def headlines_feed():
    """
    Plain listing of the headlines + analysis generated by the twice-daily
    full pipeline (publish_edition()/process_current_edition() already run
    this — this route just reads what they wrote). Falls back to a live
    top-stories query if no edition has been published yet (fresh install).
    """
    per_page = 10
    page = max(1, request.args.get("page", 1, type=int) or 1)

    latest_edition = Edition.query.filter_by(published=True).order_by(Edition.created_at.desc()).first()

    if latest_edition:
        all_edition_stories = latest_edition.edition_stories.order_by(EditionStory.rank).all()
        total_stories = len(all_edition_stories)
        start = (page - 1) * per_page
        stories = annotate_edition_story_flags(all_edition_stories[start:start + per_page])
        edition_label = f"{latest_edition.edition_type.title()} Edition — {latest_edition.date.strftime('%B %d, %Y')}"
    else:
        from sqlalchemy import func
        cutoff = datetime.utcnow() - timedelta(days=1)
        all_stories = Story.query.join(Article).group_by(Story.id).having(
            func.count(Article.id) > 1
        ).filter(
            Story.created_at >= cutoff,
            Story.headline_score > 0
        ).order_by(Story.headline_score.desc()).limit(20).all()
        total_stories = len(all_stories)
        start = (page - 1) * per_page
        stories = all_stories[start:start + per_page]
        edition_label = "Latest Headlines"

    for story in stories:
        apply_aggregator_filter(story)

    total_pages = max(1, (total_stories + per_page - 1) // per_page)

    return render_template(
        "headlines_feed.html",
        stories=stories,
        edition_label=edition_label,
        edition=latest_edition,
        page=page,
        total_pages=total_pages,
        has_next=page < total_pages,
        has_prev=page > 1,
        topics=Topic.query.filter_by(is_active=True).order_by(Topic.sort_order).all(),
        active_nav="headlines",
    )


@public.route("/story/<int:story_id>")
def view_story(story_id):
    from sqlalchemy.orm import joinedload
    story = Story.query.options(
        joinedload(Story.articles).joinedload(Article.outlet)
    ).get_or_404(story_id)

    ollama_online = check_ollama_status()

    apply_aggregator_filter(story)

    return render_template(
        "story.html",
        story=story,
        ollama_online=ollama_online,
        topics=Topic.query.filter_by(is_active=True).order_by(Topic.sort_order).all(),
    )


@public.route("/article/<int:article_id>")
def view_article(article_id):
    article = Article.query.get_or_404(article_id)
    ollama_online = check_ollama_status()

    return render_template(
        "article.html",
        article=article,
        ollama_online=ollama_online,
        topics=Topic.query.filter_by(is_active=True).order_by(Topic.sort_order).all(),
    )


@public.route("/ollama-status")
def ollama_status():
    # Unauthenticated route -- only the boolean, never the host/role, which
    # would otherwise leak internal network details (e.g. a LAN IP) to anyone.
    # The full detail is available to admins at admin.ollama_status_detail.
    return jsonify({"online": check_ollama_status()})


@public.route("/meili-status")
def meili_status():
    return jsonify({"online": meili_healthcheck()})
