"""add image_url to articles

Revision ID: 894b9d0caad3
Revises: 37ac048a5fea
Create Date: 2026-03-27 05:09:21.606383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894b9d0caad3'
down_revision = '37ac048a5fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
